os: linux
language: cpp
before_install:
- sudo apt-get update
- sudo apt-get -y install python-pip
- sudo pip install urllib3[secure] --upgrade
- sudo -H pip install -r requirements.txt
script:
- make lib/CWrapper.so
- sudo python2.7 setup.py install
- python2.7 examples/test1.py
- python2.7 examples/test2.py
- python2.7 examples/uq_pcn.py
